#include "common.h"
#ifndef IOCTL_H
#define IOCTL_H

#define IOCTL_FILE_LOG CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_PROC_LOG CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)


NTSTATUS CloneFileInfo(PIRP Irp, PIO_STACK_LOCATION IrpIoStack, PULONG InfoSize);

NTSTATUS IoControl(PDEVICE_OBJECT Device, PIRP Irp);

#endif